[build]
  # Build command for Vite
  command = "npm run build"
  
  # Directory to publish (Vite builds to 'dist' by default)
  publish = "dist"
  
  # Environment variables
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "9"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache JavaScript and CSS files
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA routing - redirect all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Preview branch settings
[context.branch-deploy]
  command = "npm run build"

# Optional: Dev branch settings
[context.dev]
  command = "npm run build" 